Add UNet3DTrainer (base class for training UNet3D in PyTorch CUDA and PyTorch/XLA)
thisisalbertliang/training pull request #9
Opened 2022-03-18 23:11 UTC by thisisalbertliang

Resolve #8 (partially)

We hope to refactor the `training` module into a more readable and extensible `trainer` package.

The `trainer` package uses polymorphism (the base class is `UNet3DTrainer` & the concrete sub-classes are `CUDATrainer` and `XLATrainer`) to toggle between training with CUDA and training with PT-XLA during runtime.

For more details, see b/224290413

2022-03-22 00:48 UTC, miladm requested changes
Thanks @thisisalbertliang!

I add a few comments below.

2022-03-22 00:48 UTC, miladm commented on image_segmentation/pytorch/runtime/trainer/unet3d_trainer.py
> +    """Base class for training UNet3D in PyTorch CUDA and PyTorch/XLA"""
I'd not specify CUDA and PyTorc/XLA. You are building this to be widely extensible to any backend framework. 

Suggestion: "Base class for training UNet3D in PyTorch"

2022-03-22 00:48 UTC, miladm commented on image_segmentation/pytorch/runtime/trainer/unet3d_trainer.py
> +        self.model.to(device)
nit: `self.device`

2022-03-22 00:48 UTC, miladm commented on image_segmentation/pytorch/runtime/trainer/unet3d_trainer.py
> +        self.loss_fn.to(device)
ditto

2022-03-22 00:48 UTC, miladm commented on image_segmentation/pytorch/runtime/trainer/unet3d_trainer.py
> +                loss_value = reduce_tensor(loss_value).detach().cpu().numpy()
Do we know if this operation is necessary for a XLA device? How about a TPU device?

See this for [reference](https://github.com/pytorch/pytorch/blob/master/torch/multiprocessing/reductions.py#L139-L276)

2022-03-22 21:38 UTC, thisisalbertliang commented on image_segmentation/pytorch/runtime/trainer/unet3d_trainer.py
> +    """Base class for training UNet3D in PyTorch CUDA and PyTorch/XLA"""
Thanks for the suggestion. I just changed the docstring to `"""Base class for training UNet3D in PyTorch"""`

2022-03-22 21:39 UTC, thisisalbertliang commented on image_segmentation/pytorch/runtime/trainer/unet3d_trainer.py
> +        self.model.to(device)
done.

2022-03-22 21:39 UTC, thisisalbertliang commented on image_segmentation/pytorch/runtime/trainer/unet3d_trainer.py
> +        self.loss_fn.to(device)
done.

2022-03-23 01:52 UTC, thisisalbertliang commented on image_segmentation/pytorch/runtime/trainer/unet3d_trainer.py
> +                loss_value = reduce_tensor(loss_value).detach().cpu().numpy()
Thanks for bringing this up.

I just confirmed that this all-reduce op is indeed necessary. I modified the train loop to print the loss value before & after the all-reduce op:
```
print(f"ALBERT DEBUG [*** RANK {get_rank()} ***]: loss_value BEFORE reduce: {loss_value}")
loss_value = reduce_tensor(loss_value).detach().cpu().numpy()
print(f"ALBERT DEBUG [*** RANK {get_rank()} ***] : loss_value AFTER reduce: {loss_value}")
```
and ran the code on TPU v3-8. This is the output log I got for one iteration:
```
ALBERT DEBUG [*** RANK 6 ***]: loss_value BEFORE reduce: 1.0074005126953125
ALBERT DEBUG [*** RANK 2 ***]: loss_value BEFORE reduce: 1.009411334991455
ALBERT DEBUG [*** RANK 3 ***]: loss_value BEFORE reduce: 0.9671453237533569
ALBERT DEBUG [*** RANK 0 ***]: loss_value BEFORE reduce: 1.020106554031372
ALBERT DEBUG [*** RANK 1 ***]: loss_value BEFORE reduce: 0.993670642375946
ALBERT DEBUG [*** RANK 4 ***]: loss_value BEFORE reduce: 0.9977484345436096
ALBERT DEBUG [*** RANK 5 ***]: loss_value BEFORE reduce: 1.002981424331665
ALBERT DEBUG [*** RANK 7 ***]: loss_value BEFORE reduce: 0.9892218112945557
ALBERT DEBUG [*** RANK 1 ***] : loss_value AFTER reduce: 0.9984608888626099
ALBERT DEBUG [*** RANK 6 ***] : loss_value AFTER reduce: 0.9984608888626099
ALBERT DEBUG [*** RANK 7 ***] : loss_value AFTER reduce: 0.9984608888626099
ALBERT DEBUG [*** RANK 2 ***] : loss_value AFTER reduce: 0.9984608888626099
ALBERT DEBUG [*** RANK 5 ***] : loss_value AFTER reduce: 0.9984608888626099
ALBERT DEBUG [*** RANK 3 ***] : loss_value AFTER reduce: 0.9984608888626099
ALBERT DEBUG [*** RANK 4 ***] : loss_value AFTER reduce: 0.9984608888626099
ALBERT DEBUG [*** RANK 0 ***] : loss_value AFTER reduce: 0.9984608888626099
```

As shown above, the all-reduce op is indeed necessary for aggregating the loss value.

2022-03-24 02:26 UTC, will-cromar approved these changes

2022-03-24 19:12 UTC, miladm approved these changes
LGTM

Thanks @thisisalbertliang!

2022-03-25 20:00 UTC, merged